---
- name: "platformsh-cli | Tap platformsh-cli"
  homebrew_tap:
    name: platformsh/tap
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'platformsh/tap' not in homebrew_taps"
  notify:
    - Get taps

- name: "platformsh-cli | Install platformsh-cli"
  homebrew:
    name: platformsh/tap/platformsh-cli
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'platformsh/tap/platformsh-cli' in homebrew_outdated_packages or 'platformsh-cli' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages