---
- name: "platformsh-cli | Install platformsh-cli"
  homebrew:
    name: platformsh/tap/platformsh-cli
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"