---
- name: "Disk | Check weather volume already exists"
  command: "diskutil apfs list"
  register: diskutil_list

- name: "Disk | Get container"
  set_fact:
    disk_container: "{{ diskutil_list.stdout | regex_search('Container\\sdisk[0-9]\\s', multiline=True) | regex_search('disk[0-9]') }}"
  when:
    - "'Projects' not in diskutil_list.stdout"

- name: "Disk | Create Projects Volume"
  command: "diskutil apfs addVolume {{ disk_container }} apfs Projects"
  when:
  - "'Projects' not in diskutil_list.stdout"