#!/usr/bin/env bash

# Platform.sh / Upsun
alias psh="platform"
alias pimcore="PLATFORMSH_CLI_SESSION_ID=pimcore_paas PLATFORMSH_CLI_API_URL=https://api.pimcore.cloud PLATFORMSH_CLI_AUTH_URL=https://auth.pimcore.cloud/ PLATFORMSH_CLI_API_VENDOR_FILTER=pimcore platform"
alias shopware="PLATFORMSH_CLI_SESSION_ID=shopware_paas PLATFORMSH_CLI_API_URL=https://proxy.shopware.com PLATFORMSH_CLI_AUTH_URL=https://psh-auth.shopware.com/ PLATFORMSH_CLI_API_VENDOR_FILTER=shopware platform"

# Deployer
alias dep="/Users/matthiashamacher/.composer/vendor/bin/dep"

# SSH Config
alias ssheditw='nvim ~/.ssh/configs/work.config'
