#!/usr/bin/env bash

# Run dotfiles
alias dotfiles="~/.dotfiles/bin/dotfiles"
alias cz='chezmoi'
alias op-login='eval $(op signin --chache)'

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"


# Shortcuts
# Tools
alias psh="platform"
#alias k="kubectl"
#alias tf="terraform"
alias dbii="docker buildx imagetools inspect"
alias dep="/Users/matthiashamacher/.composer/vendor/bin/dep"
alias pimcore="PLATFORMSH_CLI_SESSION_ID=pimcore_paas PLATFORMSH_CLI_API_URL=https://api.pimcore.cloud PLATFORMSH_CLI_AUTH_URL=https://auth.pimcore.cloud/ PLATFORMSH_CLI_API_VENDOR_FILTER=pimcore platform"
alias shopware="PLATFORMSH_CLI_SESSION_ID=shopware_paas PLATFORMSH_CLI_API_URL=https://proxy.shopware.com PLATFORMSH_CLI_AUTH_URL=https://psh-auth.shopware.com/ PLATFORMSH_CLI_API_VENDOR_FILTER=shopware platform"
alias j="just"

# grep
# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# Misc
# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Reload the shell (i.e. invoke as a login shell)
alias reload="source ~/.zprofile"

# Edit aliases
alias aliases="nvim ~/.aliases"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Edit nvim config
alias vimedit="cd ~/.config/nvim && nvim ."

# SSH
# Copy SSH Key
alias sshcopy='pbcopy < ~/.ssh/id_ed25519.pub'

# Edit SSH Config
alias ssheditm='nvim ~/.ssh/config'
alias ssheditw='nvim ~/.ssh/configs/work.config'
alias ssheditp='nvim ~/.ssh/configs/private.config'
