---
- name: "symfony-cli | Tap symfony-cli"
  homebrew_tap:
    name: symfony-cli/tap
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: "symfony-cli | Install symfony-cli"
  homebrew:
    name: symfony-cli/tap/symfony-cli
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"