---
- name: "Raycast | Install Raycast"
  homebrew:
    name: raycast
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'raycast' in homebrew_outdated_packages or 'raycast' in homebrew_installed_packages"