---
- name: "Dock | Install dockutil"
  homebrew:
    name: dockutil
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: "Dock | Remove items"
  ansible.builtin.include_tasks: remove-items.yml

- name: "Dock | Add items"
  ansible.builtin.include_tasks: add-items.yml