---
default_roles:
  - actionlint
  - amphetamine
  - ansible
  - arc
  - bartender
  - bat
  - bitwarden
  - cleanmymac
  - cleanshot
  - composer
  - disk
  - displaylink
  - dock
  - finder
  - fzf
  - git
  - gnupg
  - hadolint
  - homebrew
  - inkdrop
  - jetbrains_toolbox
  - jq
  - just
  - mac_app_store
  - make
  - neovim
  - node
  - onepassword
  - orbstack
  - php
  - pinentry_mac
  - platformsh_cli
  - prettier
  - raycast
  - rectangle
  - slack
  - spotify
  - ssh
  - symfony_cli
  - tower
  - transmit
  - visual_studio_code
  - warp
  - wireguard
  - yamllint
  - zoom
  - zoxide
  - zsh
