default_roles:
  - 1password
  - amphetamine
  - arc
  - bartender
  - bat
  - bitwarden
  - cleanmymac
  - cleanshot
  - composer
  - disk
  - displaylink
  - dock
  - finder
  - fzf
  - git
  - gnupg
  - homebrew
  - inkdrop
  - jetbrains-toolbox
  - jq
  - just
  - mac-app-store
  - make
  - neovim
  - node
  - orbstack
  - php
  - pinentry-mac
  - platformsh-cli
  - raycast
  - rectangle
  - slack
  - spotify
  - symfony-cli
  - tower
  - transmit
  - visual-studio-code
  - warp
  - wireguard
  - zoxide
  - zsh
