---
projects_volume_prefix: "/Volumes/Projects"

projects_github_folders_prefi: Github
projects_github_folders:
  - Pimcore

projects_private_folders_prefix: Private
projects_private_folders:
  - Advent of Code
  - Random Stuff
  - Random Stuff/TLDR Mail Parser

projects_work_folders_prefix: basecom
projects_work_folders:
  - Pimcore
  - Pimcore/Bundles
  - Pimcore/Customers
  - Pimcore/Teamwork
  - Pimcore/Teamwork/External Resources
  - Pimcore/Teamwork/Tools
  - Pimcore/Teamwork/Training
  - Pimcore/Templates
  - Random Stuff
  - Open Source
