---
projects_volume_prefix: /Volumes/Projects

basic_folders:
  - Random Stuff

projects_open_source_folders_prefix: Open Source
projects_open_source_folders:
  - Pimcore

projects_private_folders_prefix: Private
projects_private_folders:
  - Advent of Code

projects_basecom_folders_prefix: basecom
projects_basecom_folders:
  - Pimcore
  - Pimcore/Bundles
  - Pimcore/Customers
  - Pimcore/Teamwork
  - Pimcore/Teamwork/External Resources
  - Pimcore/Teamwork/Tools
  - Pimcore/Teamwork/Training
  - Pimcore/Templates
  - Open Source

projects_elternsprechtag_digital_folders_prefix: Elternsprechtag Digital
projects_elternsprechtag_digital_folders:
  - Tools
