---
- name: Run Darwin Tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: "gnupg | Make sure ~/.gnupg exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory
    mode: "0700"

- name: "gnupg | Configure ~/.gnupg/gpg.conf"
  ansible.builtin.copy:
    src: gpg.conf
    dest: "{{ ansible_user_dir }}/.gnupg/gpg.conf"
    mode: "0600"

- name: "gnupg | Configure ~/.gnupg/gpg-agent.conf"
  ansible.builtin.copy:
    src: gpg-agent.conf
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    mode: "0600"
  notify:
    - Restart gpg agent

- name: "gnupg | Check for keys"
  command: gpg --list-keys
  register: keys

- name: "gnupg | Copy gpg keys"
  ansible.builtin.copy:
    dest: "/tmp/gpg-keys.gpg"
    content: "{{ gpg_keys }}"
    mode: "0600"
  no_log: true
  when:
    - "'39EE597BDAF8C4F39CED2708E1170DD5A5F43A63' not in keys.stdout or '195D56FF708A71582624D63993B4DDA9DDC53860' not in keys.stdout or 'FC9AE97AB77427D3D673CBB24C3B94642870B7E8' not in keys.stdout"

- name: "gnupg | Import gpg keys"
  ansible.builtin.command:
    cmd: gpg --import /tmp/gpg-keys.gpg
  when:
    - "'39EE597BDAF8C4F39CED2708E1170DD5A5F43A63' not in keys.stdout or '195D56FF708A71582624D63993B4DDA9DDC53860' not in keys.stdout or 'FC9AE97AB77427D3D673CBB24C3B94642870B7E8' not in keys.stdout"

- name: "gnupg | Delete gpg keys file"
  ansible.builtin.file:
    path: "/tmp/gpg-keys.gpg"
    state: absent
  when:
    - "'39EE597BDAF8C4F39CED2708E1170DD5A5F43A63' not in keys.stdout or '195D56FF708A71582624D63993B4DDA9DDC53860' not in keys.stdout or 'FC9AE97AB77427D3D673CBB24C3B94642870B7E8' not in keys.stdout"

- name: "gnupg | Copy ownertrust"
  ansible.builtin.copy:
    dest: "/tmp/ownertrust-gpg.txt"
    content: "{{ gpg_ownertrust }}"
    mode: "0600"
  no_log: true
  when:
    - "'ultimate' not in keys.stdout"

- name: "gnupg | Import ownertrust"
  ansible.builtin.command:
    cmd: gpg --import-ownertrust /tmp/ownertrust-gpg.txt
  when:
    - "'ultimate' not in keys.stdout"

- name: "gnupg | Delete ownertrust file"
  ansible.builtin.file:
    path: "/tmp/ownertrust-gpg.txt"
    state: absent
  when:
    - "'ultimate' not in keys.stdout"
