---
- name: SSH | Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: SSH | Copy SSH keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "{{ '.pub' in ssh_key_item.key | ternary('0600', '0644') }}"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_keys | default({}) | dict2items }}"

- name: SSH | Copy config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    src: config
    mode: "0600"

- name: SSH | Ensure ~/.ssh/configs directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/configs"
    state: directory
    mode: "0700"

- name: SSH | Copy custom configs
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/configs/{{ ssh_config_item.key }}"
    content: "{{ ssh_config_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_config_item
  with_items: "{{ ssh_configs | default({}) | dict2items }}"
