---
- name: SSH | Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: SSH | Copy SSH private keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ private_key.key }}"
    content: "{{ private_key.value }}"
    mode: "0600"
  loop_control:
    loop_var: private_key
    label: "{{ private_key.key }}"
  with_items: "{{ ssh_private_keys | default({}) | dict2items }}"

- name: SSH | Copy SSH public keys
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ public_key.key }}"
    content: "{{ public_key.value }}"
    mode: "0644"
  loop_control:
    loop_var: public_key
    label: "{{ public_key.key }}"
  with_items: "{{ ssh_public_keys | default({}) | dict2items }}"

- name: SSH | Copy config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    src: config
    mode: "0600"

- name: SSH | Ensure ~/.ssh/configs directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/configs"
    state: directory
    mode: "0700"

- name: SSH | Copy custom configs
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/configs/{{ ssh_config_item.key }}"
    content: "{{ ssh_config_item.value }}"
    mode: "0600"
  loop_control:
    loop_var: ssh_config_item
    label: "{{ ssh_config_item.key }}"
  with_items: "{{ ssh_configs | default({}) | dict2items }}"
