---
- name: "Warp | Install Warp"
  homebrew:
    name: warp
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'warp' in homebrew_outdated_packages or 'warp' not in homebrew_installed_packages"
