---
- name: "Arc | Install Arc"
  homebrew:
    name: arc
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'arc' in homebrew_outdated_packages or 'arc' in homebrew_installed_packages"
