---
- name: Zsh | Copy .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: "{{ ansible_user_dir }}/.zprofile"
    mode: "0644"

- name: Zsh | Copy .profile
  ansible.builtin.copy:
    src: .profile
    dest: "{{ ansible_user_dir }}/.profile"
    mode: "0644"

- name: Zsh | Copy .aliases
  ansible.builtin.copy:
    src: .aliases
    dest: "{{ ansible_user_dir }}/.aliases"
    mode: "0644"

- name: Zsh | Copy .functions
  ansible.builtin.copy:
    src: .functions
    dest: "{{ ansible_user_dir }}/.functions"
    mode: "0644"

- name: Zsh | Copy .exports
  ansible.builtin.copy:
    src: .exports
    dest: "{{ ansible_user_dir }}/.exports"
    mode: "0644"

- name: Zsh | Copy .osx
  ansible.builtin.copy:
    src: .osx
    dest: "{{ ansible_user_dir }}/.osx"
    mode: "0644"
