---
- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: "Git | Set user.signingkey"
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ git_signingkey }}"

- name: "Git | Set commit.gpgsign"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: "Git | Set gpg.program"
  community.general.git_config:
    name: gpg.program
    scope: global
    value: /usr/local/bin/gpg

- name: "Git | Set gpg.format"
  community.general.git_config:
    name: gpg.format
    scope: global
    value: openpgp

- name: "Git | Set core.excludesfile"
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: ~/.gitignore

- name: "Git | Set core.whitespace"
  community.general.git_config:
    name: core.whitespace
    scope: global
    value: space-before-tab,-indent-with-non-tab,trailing-space

- name: "Git | Set core.trustctime"
  community.general.git_config:
    name: core.trustctime
    scope: global
    value: false

- name: "Git | Set core.precomposeunicode"
  community.general.git_config:
    name: core.precomposeunicode
    scope: global
    value: false

- name: "Git | Set core.untrackedCache"
  community.general.git_config:
    name: core.untrackedCache
    scope: global
    value: true

- name: "Git | Set apply.whitespace"
  community.general.git_config:
    name: apply.whitespace
    scope: global
    value: fix

- name: "Git | Set color.ui"
  community.general.git_config:
    name: color.ui
    scope: global
    value: auto

- name: "Git | Set diff.renames"
  community.general.git_config:
    name: diff.renames
    scope: global
    value: copies

- name: "Git | Set diff.colorMoved"
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra

- name: "Git | Set diff.bin.textconv"
  community.general.git_config:
    name: diff.bin.textconv
    scope: global
    value: hexdu

- name: "Git | Set help.autocorrect"
  community.general.git_config:
    name: help.autocorrect
    scope: global
    value: 1

- name: "Git | Set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: "Git | Set push.autoSetupRemove"
  community.general.git_config:
    name: push.autoSetupRemove
    scope: global
    value: true

- name: "Git | Set gpg.ssh.program"
  community.general.git_config:
    name: gpg.ssh.program
    scope: global
    value: /Applications/1Password.app/Contents/MacOS/op-ssh-sign

- name: "Git | Set tag.gpgsign"
  community.general.git_config:
    name: tag.gpgsign
    scope: global
    value: true

- name: "Git | Configure ~/.gitignore"
  ansible.builtin.copy:
    src: .gitignore
    dest: "{{ ansible_user_dir }}/.gitignore"
    mode: "0600"