---
- name: Git | Check which repos are already cloned
  ansible.builtin.stat:
    path: "{{ git_repo.path }}"
  register: existing_repositories
  loop_control:
    loop_var: git_repo
    label: "{{ git_repo.name }}"
  loop: "{{ git_repos + private_git_repos }}"
  ignore_errors: true

- name: Git | Clone missing repos
  ansible.builtin.command:
    cmd: "git clone {{ item.git_repo.url }} {{ item.git_repo.path }}"
  register: result
  loop_control:
    label: "{{ item.git_repo.name }}"
  with_items: "{{ existing_repositories.results }}"
  changed_when:
    - result.rc != 0
  when:
    - not item.stat.exists
