---
- name: Homebrew | Check installed packages
  ansible.builtin.command:
    cmd: "brew list"
  register: installed_result
  changed_when:
    - homebrew_installed_packages is undefined or installed_result.stdout != homebrew_installed_packages
  check_mode: false

- name: Homebrew | Determine installed packages
  ansible.builtin.set_fact:
    homebrew_installed_packages: "{{ installed_result.stdout }}"
  when:
    - installed_result.changed
