---
- name: "slack | Install slack"
  homebrew:
    name: slack
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: "Slack | Add to dock"
  ansible.builtin.include_tasks: ../../dock/tasks/dock-add.yml
  vars:
    item:
      name: Slack
      path: "/Applications/Slack.app/"

- name: "Slack | Set correct position"
  ansible.builtin.include_tasks: ../../dock/tasks/dock-position.yml
  vars:
    item:
      name: Slack
      pos: 4