---
- name: "node | Install node"
  homebrew:
    name: node
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'node' in homebrew_outdated_packages or 'node' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages