---
- name: Mac App Store CLI (mas) | Install
  homebrew:
    name: mas
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'mas' in homebrew_outdated_packages or 'mas' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages

- import_tasks: installed-apps.yml
