---
- name: Mac App Store CLI (mas) | Check installed apps
  command: "mas list"
  register: installed_result
  changed_when: false
  check_mode: false

- name: Mac App Store CLI (mas) | Determine installed apps
  set_fact:
    mas_installed_apps: "{{ installed_result.stdout }}"
