---
- name: "Amphetamine | Install Amphetamine"
  ansible.builtin.command: "mas install 937984704"
  register: mas_install_result
  changed_when:
    - mas_install_result.rc != 0
  when:
    - "'937984704' not in mas_installed_apps"

- name: Update installed apps
  ansible.builtin.include_tasks: roles/mac_app_store/tasks/installed-apps.yml
  when:
    - mas_install_result.changed
