---
dependencies:
  - role: orbstack
  - role: composer
  - role: platformsh_cli
  - role: neovim
  - role: ssh
  - role: homebrew
  - role: gnupg
  - role: fzf
  - role: just
  - role: lla
  - role: pulumi
  - role: zoxide
