---
- name: "php | Install php"
  homebrew:
    name: php
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'php' in homebrew_outdated_packages or 'php' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages