---
- name: "jq | Install jq"
  homebrew:
    name: jq
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'jq' in homebrew_outdated_packages or 'jq' in homebrew_installed_packages"