---
- name: "Transmit | Install Transmit"
  homebrew:
    name: transmit
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'transmit' in homebrew_outdated_packages or 'transmit' not in homebrew_installed_packages"