---
- name: "1Password | Install 1Password"
  homebrew:
    name: 1password
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: "1Password | Install 1Password-cli"
  homebrew:
    name: 1password-cli
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"

- name: "1Password | Add to dock"
  ansible.builtin.include_tasks: ../../dock/tasks/dock-add.yml
  vars:
    item:
      name: 1Password
      path: "/Applications/1Password.app/"

- name: "1Password | Set correct position"
  ansible.builtin.include_tasks: ../../dock/tasks/dock-position.yml
  vars:
    item:
      name: 1Password
      pos: 1