---
- name: "1Password | Install 1Password"
  homebrew:
    name: 1password
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'1password' in homebrew_outdated_packages or '1password' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages

- name: "1Password | Install 1Password-cli"
  homebrew:
    name: 1password-cli
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'1password-cli' in homebrew_outdated_packages or '1password-cli' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages