---
- name: "pinentry-mac | Install pinentry-mac"
  homebrew:
    name: pinentry-mac
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'pinentry-mac' in homebrew_outdated_packages or 'pinentry-mac' not in homebrew_installed_packages"
  notify:
    - Get installed packages
    - Get outdated packages