---
- name: "JetBrains Toolbox | Install JetBrains Toolbox"
  homebrew:
    name: jetbrains-toolbox
    state: latest
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"
  when:
    - "'jetbrains-toolbox' in homebrew_outdated_packages or 'jetbrains-toolbox' not in homebrew_installed_packages"