---
- name: See if Dock item exists
  ansible.builtin.command: "dockutil --find '{{ item.name }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false

- name: Get current dock section from output
  ansible.builtin.set_fact:
    current_section: "{{ dockitem_exists.stdout | regex_replace('^.*was found in (.*) at slot.*$', '\\1') }}"
  when: dockitem_exists.rc == 0

- name: Ensure Dock item exists
  ansible.builtin.command: "dockutil --add '{{ item.path }}' --label '{{ item.name }}' --after '{{ item.after }}'"
  register: result
  changed_when:
    - result.rc != 0
  when:
    - dockitem_exists.rc > 0 or dockitem_exists.rc == 0 and current_section == 'recent-apps'

- name: Pause for 7 seconds between dock changes.
  ansible.builtin.pause:
    seconds: 7
  when: dockitem_exists.rc >0 or
        dockitem_exists.rc == 0 and current_section == 'recent-apps'
