---
- name: "WireGuard | Install WireGuard"
  command: "mas install 1451685025"
  register: mas_install_result
  when:
    - "'1451685025' not in mas_installed_apps"

- name: Update installed apps
  include_tasks: roles/mac-app-store/tasks/installed-apps.yml
  when:
    - mas_install_result.changed

- name: "WireGuard | Add temporary WireGuard config folder"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/WireGuard"
    state: directory
    mode: "0755"
  when:
    - mas_install_result.changed

- name: "WireGuard | Copying configs"
  copy:
    dest: "{{ ansible_user_dir }}/Documents/WireGuard/{{ wireguard_config_item.key }}"
    content: "{{ wireguard_config_item.value }}"
    mode: "0755"
  no_log: true
  loop_control:
    loop_var: wireguard_config_item
  with_items: "{{ wireguard_config | default({}) | dict2items }}"
  when:
    - mas_install_result.changed

- name: "WireGuard | Import Wireguard Configs"
  ansible.builtin.pause:
    prompt: Manually import the config files in the App. The files are stored in ~/Documents/WireGuard. If you are done press ENTER
  when:
    - mas_install_result.changed

- name: "WireGuard | Delete configs"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Documents/WireGuard"
    state: absent
  when:
    - mas_install_result.changed